# Generated by Django 5.1 on 2024-09-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project-img')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Our works',
            },
        ),
    ]
