# Generated by Django 5.1 on 2024-09-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('project_type', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('existing_website', models.CharField(max_length=200)),
                ('desired_deadline', models.CharField(max_length=20)),
                ('estimated_budget', models.CharField(max_length=20)),
                ('preferred_start_date', models.CharField(max_length=20)),
                ('additional_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
